---
io-services:
  reader:
    class: org.jlab.epsci.stream.engine.SampaSourceEngine
    name: SMPSource
  writer:
    class: org.jlab.epsci.stream.engine.SMPWriterEngine
    name: SMPWriter
services:
  - class: org.jlab.epsci.stream.engine.SMPStreamTestEngine
    name: SMPStreamTest
  - class: sampa_service
    name: SampaService
    lang: cpp
configuration:
  io-services:
    reader:
      port1: 6000
      port2: 6001
  services:
    SMPStreamTest:
      print-interval: 10
      slot: 3
mime-types:
  - binary/data-sampa
